### ISSUE TITLE
python 3.9, 3.10 - green image

### ISSUE THREAD

**Issue by bor-lin** [agriggio/make_arq#8] opened 2023-04-26 11:16 UTC
Using python 3.9 or 3.10 images are green
(something like demosaicing none on page
https://rawpedia.rawtherapee.com/Demosaicing
).

With python 3.7 all looks good.

**Comment by agriggio** [comment] 2023-05-18 08:39
Hi @bor-lin, what camera are you using? Can you provide sample files to reproduce? Thanks!

**Comment by bor-lin** [comment] 2023-05-18 10:25
Hi,
I'am using Sony a7r4. Where to put large files?
Thanks

**Comment by abrock** [comment] 2023-05-18 11:12
> Hi, I'am using Sony a7r4. Where to put large files? Thanks

You can use something like Google drive or Dropbox. I also have that camera model so I took a quick test shot and found the same problem:

https://drive.google.com/drive/folders/1AjZ2nIw6ewCgo48EgaHhyRhO524IyWId?usp=share_link

The problem is the same in full frame and APSC-crop so I only uploaded the APSC-crop images for now.

This is what I see in RT:

![image](https://github.com/agriggio/make_arq/assets/31710/3654b5ff-8a61-491e-aa63-c22c88f49644)

**Comment by abrock** [comment] 2023-05-18 11:44
I'm using Python 3.9.2 on Debian Bullseye. I can try to install Python 3.7 if necessary.

**Comment by bor-lin** [comment] 2023-05-18 12:25
Hi,
Please find this file:
https://drive.google.com/file/d/1Zq8kQY-q8sWhyEfdWzs1YClRo-diFKgR/view?usp=sharing
Please let me know when Ican delete this file.
I have done tests using an old one gento and make_arg and new.
Thanks

**Comment by agriggio** [comment] 2023-05-18 17:00
Thanks for the samples. It turns out the problem is not a newer interpreter, but a newer version of the `tifffile` library. It should be fixed now, but it would be good if you could confirm. Thanks!

**Comment by abrock** [comment] 2023-05-18 19:03
I can confirm that it works as expected with full frame and with APSC-crop. Thank you very much for this amazing software, it's very helpful.

**Comment by agriggio** [comment] 2023-05-18 21:15
Great, closing then!

**Closed as completed by agriggio** 2023-05-18 21:15 UTC

**Comment by bor-lin** [comment] 2023-05-19 10:23
Thank you very much for adapting make_arq to the new tifffile.
I've used make_arq for many years and have been having a lot of trouble
with it recently.
There is one more problem - a quarter of the image is displayed.
Thank you again

**Comment by abrock** [comment] 2023-05-19 10:30
> There is one more problem - a quarter of the image is displayed. Thank you again

Could you upload the four images and also a screenshot showing the problem?

**Comment by bor-lin** [comment] 2023-05-19 10:35
https://drive.google.com/file/d/1CHsUE9TzLgawcghRoWQqg91WLrILF8Ry/view?usp=sharing

I have attached this to the last e-mail but is not visible

**Comment by bor-lin** [comment] 2023-05-19 10:38
I have 16 ARW and one ARQ - do you need them?

**Comment by bor-lin** [comment] 2023-05-19 10:55
16 ARW and ARQ made with yesterday make_arq

https://drive.google.com/file/d/1wHBWWARifEqfq8a1F6iGSC_Q9HuYOTFI/view?usp=sharing

Please let me know when Ican delete this file.

**Comment by abrock** [comment] 2023-05-19 11:30
I downloaded the files and I cannot reproduce the problem, if I run make_arq I get the full frame:

![image](https://github.com/agriggio/make_arq/assets/31710/c175e6e3-46c8-4973-bf35-fed984c23144)

**Comment by bor-lin** [comment] 2023-05-19 11:49
I have:
dev-lang/python-3.9.16_p3
tifffile 2023.4.12

and I have " quarter problem"

**Comment by bor-lin** [comment] 2023-05-19 12:19
I have tested:
1. without mc (ctrl-o and command)
2. without `ls ...`
Result the same - "quarter".

With:
python-3.9.0_beta5
tifffile     2023.4.12 (the same !!!)

and
ls -l _makearq.c
-rw-r--r-- 1 bor users 3518 Nov 25  2020 _makearq.c

there is full image.

**Comment by agriggio** [comment] 2023-05-19 15:04
please open a separate issue, thanks!
